### ISSUE TITLE
DATABASE_URL

### ISSUE THREAD

**Issue by cvatricks** [MoarCatz/chat-server#16]
What will be DATABASE_URL ? and How to get it ?

**Comment by illright** [comment]
It is a connection URL for a PostgreSQL database that you should have running somewhere. Depending on how you want to deploy this server and your database, your methods of obtaining it will vary.

Please note that this is an unmaintained project. As such, it will not receive much support from the authors. Unless you have a very good idea of what this project is and what do you need it for, you probably shouldn't use it or try to deploy it.
